---
version: "3.8"
services:

  # Redis
  redis:
    container_name: neuma-redis
    image: redis:alpine
    ports:
      - 6379:6379

  # Celery worker
  celery:
    container_name: neuma-celery
    build: .
    command: "celery -A scorelib worker -B -l INFO"
    env_file:
      - docker.env
    depends_on:
      - redis

  # Flower, to monitor Celery
  flower:
    container_name: neuma-flower
    image: mher/flower
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
    depends_on:
      - redis
      
  elasticsearch:
    container_name: "neuma-es"
    image: docker.elastic.co/elasticsearch/elasticsearch:7.16.2
    volumes:
      - ./data/elastic:/var/lib/elasticsearch/data
    environment:
      - cluster.name=docker-cluster
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - 9200:9200
      
volumes:
  database:
    driver: local


